ports = []
[languages.python]
language = "python"
[languages.python.run."main.py"]
name = "main.py"
path = "/workspace/PythonProject/main.py"

[languages.python.run."main copy.py"]
name = "main copy.py"
path = "/workspace/PythonProject/main copy.py"
